FROM arm32v6/node:14-alpine3.10

WORKDIR /app
COPY index.html /app/.
COPY index.js /app/.
COPY proxy.js /app/.
COPY package.json /app/.

RUN npm install --omit=dev
RUN echo "[]" > blacklist

CMD [ "node", "index.js" ]
